version: 2

models:
  - name: dim_users
    description: user + address information
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

  - name: dim_products
    description: products + how many times ordered
    columns:
      - name: product_id
    tests::
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id

  - name: fact_orders
    description: orders including line items
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id