version: 2

models:
  - name: int_orders
    description: intermediate orders model including promos
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
  - name: int_products
    description: products + how many times ordered
    columns:
      - name: product_id
    tests::
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id
  - name: int_sessions